#+TITLE: Agenda
#+TODO: TODO(t) PROCESSING(p) | DONE(d)
#+TODO: TOREVIEW(r) | REVIEWED(d)
#+TAGS: @Julia(j) @Aleks(a) @Serhii(s)
#+PRIORITIES: 1 3 2
#+PROPERTY: session *EL* 
#+PROPERTY: cache yes
# #+ARCHIVE: ::* Archived
#+ARCHIVE: %s_done::


* Frontend
** PROCESSING [#2] Jarman Theme Light Style, live coding :@Julia:@Aleks:@Serhii:
   - [X] global font
   - [X] global background
   - [X] global foreground
   - [ ] rewrite styles config
   - [ ] unifing styles in UI
   - [ ] removing unnessesary borders.
   - [X] removing unnessesary font override         
** PROCESSING [#1] Frontend refactorization
*** TODO Icons                                                       :@Julia:
    - [ ] Plus icon. Replace =plus= icon, make add width, and make only one color. And =minus= do little bit higher, also =x= icon
    - [ ] refresh-reload icons, increase arrow, and make some distance between each other. Only one color
    - [ ] Left/Right direction one arrow. like =->= and =<-=
    - [ ] =odt export= file icon
    - [ ] logout icon.
    - [ ] =Select all=, is like "checkbox" =[V]=
    - [ ] Pay icon. (hrywna) + (dolar)
    - [ ] До лупи додати кінець, одноколірна.
     
*** TODO Main view                                                   :@Aleks:
    - [X] On tabs replace non-active tab on more brighter color.
    - [X] ON tabs replace `x` icon on one color.
    - [-] change slider menu [3/4]
      - [X] to `close-app` also add `logout`
      - [X] remove `Change work mode`, and add optino to `.jarman` which will be add "key icon" to slider menu.
      - [ ] create slider menu `.jarman` configuraion.
      - [X] Remove `Db visuliser` from left bar.
    - [X] Font. Select automaticaly Font's for all GUI components, becuase all plugins also must inherit those.
    - [-] Menu bar [6/7]
      - [ ] increase slider menu size, and put this option to `.jarman` or `.jarman.d/config` directory, for you taste.
      - [X] Levels. Add spaces inside expand buttons groups.
      - [X] For levels in expand button please choose at least Six color levels, and repeat if user create level 7 or 8.
      - [X] For levels choose rainbow colors but make it little bit more pastel.
      - [X] Change all black font's on closelly to black. Use some *dark-gray*, with blue-direction - `#030D1C` as example.
      - [X] Also for expand buttons use bold ubuntu fonts (looks little crappy).
      - [X] Chnage ordering items in menubar. At first place user must saw all buisness tables, and next any other *setting* or *db visualizer* etc.

*** TODO Table.clj                                                   :@Aleks:
    - [X] remove 1pixel black border for right table.
    - [ ] text "hide" replace on julia (not created at that moment) left arrow, and background fill with one gray color, as "tab", or left section in table.clj, where components is.
    - [X] make icon smaller, on 10-20%
    - [X] Move Table title to left side (nope, on center looks better), and colorize in "ocean blue" color, julia use it in login panel.

*** TODO Service Periods plugins                                     :@Aleks:
    - [ ] Expand buttons [0/7]
      - [ ] Buttons must be resizable, and scaled to window width.
      - [ ] Not hide expanded button, when checkbox was clicked. Julia add coments inside plugin, about this issue (find "TODO" mark)
      - [ ] make less color differencess between embaded expand buttons.
      - [ ] Also in future change `+/-` icons.
      - [ ] For Enterperneur use this format style "X-kom, 400 zl", money color must be pastel green.
      - [ ] For Service Contract use this format stlye notation "30-12-2020 - 04-01-2021,  200 zl", money also in green.
      - [ ] For Service Months use ths format style notation "01-01-2020 - 04-01-2021,  100 zl", money also in pastel green.
    - [ ] Julia call it *insert-space*, is section where we adding new service contract. Rewrite whole panel, but keep logic as we create before.
    - [ ] After you click on one month, you can edit all service contract month payments. You can edit, only if month wasn't payed. Rewrite Julia view, on your implementation. I think better be when all those month fields be in one line.
** TODO Any other task
** PROCESSING [#3] Cannot compile                            :@Aleks:@Serhii:
   To big description with some code evaluation etc.
   put cursor on link and make =C-c C-o= which open link to editing
   [[file:issues/t_01.org][read more...]]
   
** TOREVIEW Clojure case you want to explain                        :@Serhii:
   Is some complex situation what we have
   [[file:issues/t_02.org][take a look]]
   Maybe this is really nice discription

** DONE fdsaofdsfdsam
   CLOSED: [2021-08-31 Tue 19:32]
   ddfsajkl
*** fdslajl
    fdsfdas    
    
** DONE fdsaom
   CLOSED: [2021-08-30 Mon 16:48]
   ddfsajkl
*** fdslajl
    fdsfdas

* Backend
** TODO [#2] service_period.clj | sort contract list         :@Julia:@Serhii:
*** [ ] sorting contract by date
*** [ ] colorize contract by active-nonactive depend on current date
** TODO [#1] themes plugin system                            :@Aleks:@Serhii:
   - Note taken on [2021-09-02 чт 09:16] \\
     With relation to our conversation, @Morfeu5z please make namespace like jarman.gui.style,
     when you put simple variables . to customizing all styles per compoennt, after you done those taks,
     call me, for "talk" about idiomatic direction of naming for styles(i mean lexical abstracution you use
     to specifying variables style). As you remember i warn you not create variables like "button-one-border-bottom" etc.
     
     Try to minimize count of those varaibles(mean not more 50 etc. it's not about repeating colors, it's about abstraction division)
*** [ ] make this file, but not start integrate it to system, just create file. :@Aleks:    
*** [ ] try to prepare some graphical view for changing theme. Discribe one theme as ", " :@Aleks:    
*** [ ] create plugin declaration for themes.                       :@Serhii:

* Infrastructure
* Documentations
