#+TITLE: Agenda
#+TODO: TOREVIEW(r) PROCESSING(p) TODO(t) PLANNED(s) | DONE(d)
#+TAGS: @Aleks(a) @Serhii(s) @Julia(j)
#+PRIORITIES: 1 3 2
#+PROPERTY: session *EL* 
#+PROPERTY: cache yes
#+ARCHIVE: %s_done::
#+STARTUP: overview

* Bugtrack
** TODO 006 variable list error
   In varialbe list, when i click on variable i get this error
   #+begin_example
   Exception in thread "AWT-EventQueue-1" clojure.lang.ArityException: Wrong number of args (1) passed to: jarman.gui.gui-vars-listing/var-content/fn--19067/fn--19068
        at clojure.lang.AFn.throwArity(AFn.java:429)
        at clojure.lang.AFn.invoke(AFn.java:32)
        at jarman.gui.popup$popup.invokeStatic(popup.clj:132)
        at jarman.gui.popup$popup.invoke(popup.clj:96)
        at jarman.gui.popup$build_popup.invokeStatic(popup.clj:159)
        at jarman.gui.popup$build_popup.invoke(popup.clj:151)
        at jarman.gui.gui_vars_listing$var_content$fn__19067.invoke(gui_vars_listing.clj:76)
        at seesaw.event$fire.invokeStatic(event.clj:263)
        at seesaw.event$fire.invoke(event.clj:262)
        at seesaw.event$fn$reify__2782.mouseClicked(event.clj:290)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6638)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at seesaw.core.proxy$javax.swing.JLabel$Tag$fd407141.processMouseEvent(Unknown Source)
        at java.desktop/java.awt.Component.processEvent(Component.java:6400)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at seesaw.core.proxy$javax.swing.JLabel$Tag$fd407141.processEvent(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
   #+end_example
** TODO 005 Metadata fix styles
   Metadata Editor, fix style, and Reload Metadata inside cache.
** TODO 004 Monospace Font for View Editors
** TODO 003 no license NullPointer
   When i *NOT* choosed license file, i saw NullPointer.
   #+begin_src 
Exception in thread "AWT-EventQueue-1" java.lang.NullPointerException
        at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
        at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
        at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
        at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
        at java.base/java.util.regex.Pattern.split(Pattern.java:1261)
        at java.base/java.util.regex.Pattern.split(Pattern.java:1334)
        at clojure.string$split.invokeStatic(string.clj:224)
        at clojure.string$split.invoke(string.clj:219)
        at jarman.gui.gui_config_panel$split_path.invokeStatic(gui_config_panel.clj:140)
        at jarman.gui.gui_config_panel$split_path.invoke(gui_config_panel.clj:139)
        at jarman.gui.gui_config_panel$file_exp$fn__19175.invoke(gui_config_panel.clj:157)
        at seesaw.event$fire.invokeStatic(event.clj:263)
        at seesaw.event$fire.invoke(event.clj:262)
        at seesaw.event$fn$reify__2782.mouseClicked(event.clj:290)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6638)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at seesaw.core.proxy$javax.swing.JLabel$Tag$fd407141.processMouseEvent(Unknown Source)
        at java.desktop/java.awt.Component.processEvent(Component.java:6400)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at seesaw.core.proxy$javax.swing.JLabel$Tag$fd407141.processEvent(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
   #+end_src
** TODO 001 no settings

   When i click on Settings menu tab I got those message:
   #+begin_example
   Exception in thread "Thread-14" java.lang.NullPointerException
        at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:426)
        at jarman.logic.state$new_watcher$fn__14602.invoke(state.clj:102)
        at clojure.lang.ARef.notifyWatches(ARef.java:81)
        at clojure.lang.Atom.swap(Atom.java:41)
        at clojure.core$swap_BANG_.invokeStatic(core.clj:2352)
        at clojure.core$swap_BANG_.invoke(core.clj:2345)
        at jarman.gui.gui_config_panel$load_license$fn__19158.invoke(gui_config_panel.clj:105)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:834)
   #+end_example

* Common thread 
** PROCESSING /Refactor/. Create /jarman.gui.swing/
  should be common namespace that contain all the
  tools for working with swing.
** TODO /Refactor/. Create /jarman.lang/
  - =jarman.tools.lang=
  - =jarman.tools.org=
    
decompose =jarman.tools.lang=, and move all to the
  jarman.lang with keeping the.
** TODO [#3] /Feature/. On exit event [0/1]                    :@Aleks:@Serhii:
   - [ ] Create event when close [1/3]
     - [ ] Autoclose log stream's /:@Serhii:/
     - [X] Override window events
** PLANNED Feature. Frontend upgrade [0/4]                           :@Aleks:
*** Slider menu [0/7]
    - [ ] Move icon buttons to one transparent vertical layout - SliderBox.
    - [ ] SliderBox should be on JLayeredPane.
    - [ ] SliderBox fn hide/show - make shift animation off the screen and back. Update global state with SliderMenu occupied space. Watcher will be updating bounds and size on layouts MainMenu and FnSpace.
    - [ ] Register shortcut for hide/show in global shortcut (inside state).
    - [ ] On top mode. FnSpace will be fitted to frame and SliderMenu will be higher on layers and will cover FnSpace.
    - [ ] Default on start in ~.jarman~ configuraion - hide/show slider menu.
    - [ ] Default on start in ~.theme~ configuraion  - slider menu size.
*** Main menu [0/8]
    - [ ] Pull out main menu to MenuBox and set into JLayeredPane.
    - [ ] Watcher should changing MainMenu bounds when global state with SliderMenu occupied space will be changed. MainMenu will be properly shifted relative to the SliderMenu.
    - [ ] Hide/Show just put MainMenu into SliderMenu as icon when should be hiding and remove it from JLayeredPane. Click on icon will back MainMenu into JLayeredPane.
    - [ ] Slim right border for changing size of MainMenu. Size will be inside global state.
    - [ ] On top mode. FnSpace will be fitted to frame and MainMenu will be higher on layers and will cover FnSpace. MainMenu will be properly shifted relative to the SliderMenu.
    - [ ] Default on start in ~.jarman~ configuraion - hide/show main menu.
    - [ ] Default on start in ~.theme~ configuraion  - main menu size.
    - [ ] Add documentation how to correctly pin some components to menus. Also add more information to the Exceptions
	When i pin my panel, i get exception
	#+begin_example
	Gui view service: Cannot rerender :view-spaceWrong number of args (0) passed to: jarman.gui.gui-main-menu/default-menu-items/fn--28447
	#+end_example
	This is missunderstandable, please make throw some Exeption
*** FnSpace [0/3]
    - [ ] If on top mode will be off then FnSpace will be properly shifted relative to the SliderMenu and MainMenu.
    - [ ] If on top mode will be on then FnSpace will be always fitted to frame.
    - [ ] Watcher should changing size of FnSpace when global state with size of MainMenu or SliderMenu will be changed. FnSpace will be fitted to components inside app's frame.
** PLANNED /Feature/. Extension Manager [1/5]                          :@Aleks:
   - [X] Related to [[#alert-boxes-replacement]], fix alert boxes.
   - [ ] *FUTURE* Show extension file-tree. Alow editing file through the jarman [0/2]
     Related to [[#interaction-function-set]] use interaction to open file in tab
     - [ ] *FUTURE* GUI part of tree file-view for package folder
     - [ ] *FUTURE* Open file interaction
   - [ ] *FUTURE* Show whole information about package, from file /PandaPackage/ entity, when you click on
     special expand segment.
   - [ ] *FUTURE* =Enable/Disable= extension
     - [ ] *FUTURE* replace param in =.jarman=.
   - [ ] *FUTURE* Extention searching/install template, because repository we currently doesnt have
     You will managed plugins as list of PandaPackage records.
** PLANNED Service Period. sort contract list                       :@Serhii:
   - [ ] sorting contract by date
   - [ ] colorize contract by active-nonactive depend on current date
** Ekka todo#1 chages                                 :@Julia:@Aleks:@Serhii:
*** Підприємець
    -   ЄДРПОУ - 10 цифр довжина з переду нулями
    -   Форма власності - комбобокс
    -   Номер ПДВ

*** Point of sale
    -   Назва торгового обєкту

*** РРО
    -   повна назва
    -   Заводський номер замість серійний
    -   Десять цифр фіскальний номер
    -   Працює.непрацює якщо робить нарахування
    -   Версія -> Версія прошивки
    -   Ідентифікатор виробника -> Просто виробник назва
    -   Три поля модему замінити на тип зв'язку GPRS,Ethernet,Wireless.комбобокс. Якщо ГПРС то активний телефонний номер, якщо ні то дай компонент неактивним
    -   Телефонний номер не модема а РРО

*** Пломби
     -   Використана чи ні.

*** Ремонти
      -   остання датат контаркуту видалити
      -   Фіскальний номер
      -   Дата
      -   Причина розпломбування - комбо
      -   Технічна насправність  - список
      -   Характер насправності  - вибір
      -   Яка пломба ставиться   - додати
      -   Час(дата.година) розпломбування апарту

*** ДОговір сервісного обслуговування
       -   підприємець
       -   Сторона підписуванн
       -   Сторона замовник(директор)
       -   Список касових апаратів
       -   Тариф
       -   Реквізити
       -   Строк дії договору(дефолт на рік)
       -   Нарахунок по дням

*** Акт виконаних робіт
	-   створити
