* FTP
 Ftp server infrastructure. As root */* i mean root ftp folder dir
 FTP aims:
 - trashpanda package repository.
 - trashpanda log repository
 - trashpanda file server. 
   
 FTP root contain folders with name of program they relate. In this folder mainly must be list of packages. 
 Package - is destribution unit for trashpanda system. It may be programs, updates, plugins, parts of program wich name of folder that contain. 

* Package standart
  
  *jarman-0.1.12-windows.zip* - example name of package.

  /jarman/ - program name. Is requred by inditification by every program made by trashpanda team.
           - simple name of program/plugin, or other things you need would be.

  /0.1.12/ - version of program
           - using x.x.x pattern convinience. It mostly tip, not a rule, as rule. 
                   | | +- hotfix
                   | +--- feature
                   +----- functionality update
  /windows.zip/ - program attribute. (Declare in `*program-attr*`).
       Attribute rule: - split with dot (.) symbol
                       - thats all

 For geting three part use this regular expression formula
   #"(\w+)-(\w+\.\w+\.\w+)[-.]{0,1}(.+)"
     ----- ---------------(. or -)  --
       |          |                  +--- attributes
       |          +---------------------- x.x.x version
       +--------------------------------- program name


Replace program by update program manager
For classification system mainly using attributes. Attribute give program microinformation about package in every folder. This would be parsed by client program. 
Personaly recoment do uzing attribute: 
- /update/ - for update
- /windows/ - for specify machine or platform, where package would be run
- /plugin/ - for plugin package.

*REQUIRED* :
- all packages must had *.zip* file extension, no zipped not be viewed by ftp programs client.
- all packages must had patter described above for his autentification. 

* troubleshooting 
FTP also used for pushing to it Troubleshooting packages, or servise information. This mechanism resive to FTP server data for our next debugging it. The reson of transfering data - is send to programer infromation which they cannot fix by telefon or email, or cannot repair on distanse. Database and other. 
 Every troubleshooting event mean that to server on branch /troubleshoot was send zip package with problem file(-s) with short log.

** Troubleshooting package standart
Resived by program log package has that name stanart: 
*jarman-1.3.5-(18.04.2020-11.54)-plugin.log* - for logs
*jarman-1.3.5-(18.04.2020).zip* - for program packages
*jarman-1.3.5-(18.04.2020).db* - for db snapshot

* FTP branches:
** /troubleshoot
   Folder for sending errors from other programs.
** /jarman 
   !Root for jarman propograms. All packages must not contain any subfolders. If that be plugin, program, update or other program distribution unit, they must location in root of program-name frp path. /<progarm name>. 
** /hrtime
   !Root for hrtime propograms. All packages must not contain any subfolders. If that be plugin, program, update or other program distribution unit, they must location in root of program-name frp path. /<program name>. 
   
