{:host "trashpanda-team.ddns.net", :port 3307, :dbname "jarman"}

(defview
 permission
 :pkey
 [:user :admin]
 (jarman-table
  :name
  "repair_contract"
  :plug-place
  [:#tables-view-plugin]
  :pkey [:user]
  :tables
  [:permission]
  :model
  [:permission.permission_name :permission.configuration]
  :query
  {:columns
   (as-is
    :permission.id
    :permission.permission_name
    :permission.configuration)}))

(defview
 user
 :pkey
 [:user :admin :dev]
 (jarman-table
  :name
  "user"
  :pkey
  [:user :admin :dev]
  :plug-place
  [:#tables-view-plugin]
  :override-model
  [{:column :user.login,
    :fun
    (fn* [p1__11770#] ((c/label :text (rift (:val p1__11770#) ""))))}]
  :tables
  [:user :permission]
  :model
  [:user.first_name
   :user.last_name
   :user.login
   :permission.permission_name]
  :query
  {:inner-join [:permission],
   :column
   (as-is
    :user.id
    :user.login
    :user.password
    :user.first_name
    :user.last_name
    :permission.permission_name
    :permission.configuration
    :user.id_permission)}))

(defview
 enterpreneur
 (jarman-table
  :name
  "enterpreneur"
  :plug-place
  [:#tables-view-plugin]
  :pkey
  [:user :dev]
  :tables
  [:enterpreneur]
  :model
  (as-is
   :enterpreneur.ssreou
   :enterpreneur.ownership_form
   :enterpreneur.vat_certificate
   :enterpreneur.individual_tax_number
   :enterpreneur.director
   :enterpreneur.accountant
   :enterpreneur.legal_address
   :enterpreneur.physical_address
   :enterpreneur.contacts_information)
  :query
  {:columns
   (as-is
    :enterpreneur.id
    :enterpreneur.ssreou
    :enterpreneur.ownership_form
    :enterpreneur.vat_certificate
    :enterpreneur.individual_tax_number
    :enterpreneur.director
    :enterpreneur.accountant
    :enterpreneur.legal_address
    :enterpreneur.physical_address
    :enterpreneur.contacts_information)}))

(defview
 point_of_sale
 (jarman-table
  :name
  "point_of_sale"
  :plug-place
  [:#tables-view-plugin]
  :tables
  [:point_of_sale :enterpreneur]
  :model
  (as-is
   :point_of_sale.id_enterpreneur
   :point_of_sale.name
   :point_of_sale.physical_address
   :point_of_sale.telefons
   :enterpreneur.ssreou
   :enterpreneur.ownership_form
   :enterpreneur.vat_certificate
   :enterpreneur.individual_tax_number
   :enterpreneur.director
   :enterpreneur.accountant
   :enterpreneur.legal_address
   :enterpreneur.physical_address
   :enterpreneur.contacts_information)
  :query
  {:inner-join [:point_of_sale->enterpreneur],
   :columns
   (as-is
    :point_of_sale.id
    :point_of_sale.id_enterpreneur
    :point_of_sale.name
    :point_of_sale.physical_address
    :point_of_sale.telefons
    :enterpreneur.id
    :enterpreneur.ssreou
    :enterpreneur.ownership_form
    :enterpreneur.vat_certificate
    :enterpreneur.individual_tax_number
    :enterpreneur.director
    :enterpreneur.accountant
    :enterpreneur.legal_address
    :enterpreneur.physical_address
    :enterpreneur.contacts_information)}))

(defview
 cache_register
 (jarman-table
  :name
  "cache_register"
  :plug-place
  [:#tables-view-plugin]
  :tables
  [:cache_register :point_of_sale :enterpreneur]
  :model
  (as-is
   :cache_register.id_point_of_sale
   :cache_register.name
   :cache_register.serial_number
   :cache_register.fiscal_number
   :cache_register.manufacture_date
   :cache_register.first_registration_date
   :cache_register.is_working
   :cache_register.version
   :cache_register.dev_id
   :cache_register.producer
   :cache_register.modem
   :cache_register.modem_model
   :cache_register.modem_serial_number
   :cache_register.modem_phone_number
   :point_of_sale.id_enterpreneur
   :point_of_sale.name
   :point_of_sale.physical_address
   :point_of_sale.telefons
   :enterpreneur.ssreou
   :enterpreneur.ownership_form
   :enterpreneur.vat_certificate
   :enterpreneur.individual_tax_number
   :enterpreneur.director
   :enterpreneur.accountant
   :enterpreneur.legal_address
   :enterpreneur.physical_address
   :enterpreneur.contacts_information)
  :query
  {:inner-join
   [:cache_register->point_of_sale :point_of_sale->enterpreneur],
   :columns
   (as-is
    :cache_register.id
    :cache_register.id_point_of_sale
    :cache_register.name
    :cache_register.serial_number
    :cache_register.fiscal_number
    :cache_register.manufacture_date
    :cache_register.first_registration_date
    :cache_register.is_working
    :cache_register.version
    :cache_register.dev_id
    :cache_register.producer
    :cache_register.modem
    :cache_register.modem_model
    :cache_register.modem_serial_number
    :cache_register.modem_phone_number
    :point_of_sale.id
    :point_of_sale.id_enterpreneur
    :point_of_sale.name
    :point_of_sale.physical_address
    :point_of_sale.telefons
    :enterpreneur.id
    :enterpreneur.ssreou
    :enterpreneur.ownership_form
    :enterpreneur.vat_certificate
    :enterpreneur.individual_tax_number
    :enterpreneur.director
    :enterpreneur.accountant
    :enterpreneur.legal_address
    :enterpreneur.physical_address
    :enterpreneur.contacts_information)}))

(defview
 point_of_sale_group
 (jarman-table
  :name
  "point_of_sale_group"
  :plug-place
  [:#tables-view-plugin]
  :tables
  [:point_of_sale_group]
  :model
  (as-is
   :point_of_sale_group.group_name
   :point_of_sale_group.information)
  :query
  {:columns
   (as-is
    :point_of_sale_group.id
    :point_of_sale_group.group_name
    :point_of_sale_group.information)}))

(defview
 point_of_sale_group_links
 (jarman-table
  :name
  "point_of_sale_group_links"
  :plug-place
  [:#tables-view-plugin]
  :tables
  [:point_of_sale_group_links
   :point_of_sale_group
   :point_of_sale
   :enterpreneur]
  :model
  (as-is
   :point_of_sale_group_links.id
   :point_of_sale_group_links.id_point_of_sale_group
   :point_of_sale_group_links.id_point_of_sale
   :point_of_sale_group.group_name
   :point_of_sale_group.information
   :point_of_sale.id_enterpreneur
   :point_of_sale.name
   :point_of_sale.physical_address
   :point_of_sale.telefons
   :enterpreneur.id
   :enterpreneur.ssreou
   :enterpreneur.ownership_form
   :enterpreneur.vat_certificate
   :enterpreneur.individual_tax_number
   :enterpreneur.director
   :enterpreneur.accountant
   :enterpreneur.legal_address
   :enterpreneur.physical_address
   :enterpreneur.contacts_information)
  :query
  {:inner-join
   [:point_of_sale_group_links->point_of_sale_group
    :point_of_sale_group_links->point_of_sale
    :point_of_sale->enterpreneur],
   :columns
   (as-is
    :point_of_sale_group_links.id
    :point_of_sale_group_links.id_point_of_sale_group
    :point_of_sale_group_links.id_point_of_sale
    :point_of_sale_group.group_name
    :point_of_sale_group.information
    :point_of_sale.id_enterpreneur
    :point_of_sale.name
    :point_of_sale.physical_address
    :point_of_sale.telefons
    :enterpreneur.id
    :enterpreneur.ssreou
    :enterpreneur.ownership_form
    :enterpreneur.vat_certificate
    :enterpreneur.individual_tax_number
    :enterpreneur.director
    :enterpreneur.accountant
    :enterpreneur.legal_address
    :enterpreneur.physical_address
    :enterpreneur.contacts_information)}))

(defview
 service_contract
 (jarman-table
  :name
  "service_contract"
  :plug-place
  [:#tables-view-plugin]
  :tables
  [:service_contract :enterpreneur]
  :model
  (as-is
   :service_contract.id_enterpreneur
   :service_contract.contract_start_term
   :service_contract.contract_end_term
   :service_contract.money_per_month
   :enterpreneur.ssreou
   :enterpreneur.ownership_form
   :enterpreneur.vat_certificate
   :enterpreneur.individual_tax_number
   :enterpreneur.director
   :enterpreneur.accountant
   :enterpreneur.legal_address
   :enterpreneur.physical_address
   :enterpreneur.contacts_information)
  :query
  {:inner-join [:service_contract->enterpreneur],
   :columns
   (as-is
    :service_contract.id
    :service_contract.id_enterpreneur
    :service_contract.contract_start_term
    :service_contract.contract_end_term
    :service_contract.money_per_month
    :enterpreneur.id
    :enterpreneur.ssreou
    :enterpreneur.ownership_form
    :enterpreneur.vat_certificate
    :enterpreneur.individual_tax_number
    :enterpreneur.director
    :enterpreneur.accountant
    :enterpreneur.legal_address
    :enterpreneur.physical_address
    :enterpreneur.contacts_information)}))

(defview
 repair_contract
 (jarman-table
  :name
  "repair_contract"
  :plug-place
  [:#tables-view-plugin]
  :tables
  [:repair_contract
   :cache_register
   :point_of_sale
   :enterpreneur
   :old_seal
   :new_seal]
  :model
  (as-is
   :repair_contract.id_cache_register
   :repair_contract.id_old_seal
   :repair_contract.id_new_seal
   :repair_contract.repair_date
   :repair_contract.cause_of_removing_seal
   :repair_contract.tech_problem_description
   :repair_contract.tech_problem_type
   :repair_contract.cache_register_register_date
   :cache_register.id_point_of_sale
   :cache_register.name
   :cache_register.serial_number
   :cache_register.fiscal_number
   :cache_register.manufacture_date
   :cache_register.first_registration_date
   :cache_register.is_working
   :cache_register.version
   :cache_register.dev_id
   :cache_register.producer
   :cache_register.modem
   :cache_register.modem_model
   :cache_register.modem_serial_number
   :cache_register.modem_phone_number
   :point_of_sale.id_enterpreneur
   :point_of_sale.name
   :point_of_sale.physical_address
   :point_of_sale.telefons
   :enterpreneur.ssreou
   :enterpreneur.ownership_form
   :enterpreneur.vat_certificate
   :enterpreneur.individual_tax_number
   :enterpreneur.director
   :enterpreneur.accountant
   :enterpreneur.legal_address
   :enterpreneur.physical_address
   :enterpreneur.contacts_information
   :old_seal.seal_number
   :old_seal.datetime_of_use
   :old_seal.datetime_of_remove
   :new_seal.seal_number
   :new_seal.datetime_of_use
   :new_seal.datetime_of_remove)
  :query
  {:inner-join
   [:repair_contract->cache_register
    :cache_register->point_of_sale
    :point_of_sale->enterpreneur
    :repair_contract.id_old_seal->seal.id
    :repair_contract.id_new_seal->seal.id],
   :columns
   (as-is
    :repair_contract.id
    :repair_contract.id_cache_register
    :repair_contract.id_old_seal
    :repair_contract.id_new_seal
    :repair_contract.repair_date
    :repair_contract.cause_of_removing_seal
    :repair_contract.tech_problem_description
    :repair_contract.tech_problem_type
    :repair_contract.cache_register_register_date
    :cache_register.id_point_of_sale
    :cache_register.name
    :cache_register.serial_number
    :cache_register.fiscal_number
    :cache_register.manufacture_date
    :cache_register.first_registration_date
    :cache_register.is_working
    :cache_register.version
    :cache_register.dev_id
    :cache_register.producer
    :cache_register.modem
    :cache_register.modem_model
    :cache_register.modem_serial_number
    :cache_register.modem_phone_number
    :point_of_sale.id_enterpreneur
    :point_of_sale.name
    :point_of_sale.physical_address
    :point_of_sale.telefons
    :enterpreneur.ssreou
    :enterpreneur.ownership_form
    :enterpreneur.vat_certificate
    :enterpreneur.individual_tax_number
    :enterpreneur.director
    :enterpreneur.accountant
    :enterpreneur.legal_address
    :enterpreneur.physical_address
    :enterpreneur.contacts_information
    :old_seal.seal_number
    :old_seal.datetime_of_use
    :old_seal.datetime_of_remove
    :new_seal.seal_number
    :new_seal.datetime_of_use
    :new_seal.datetime_of_remove)}))

