* Readme 
  In this file shortedly describe how all installation process gone in system, and describe how to build your jarman pipeline. 
  Scope of this file not overviewing whole devops managment, only creation setuping file.

* Installation 
** TODO Linux 
   Currently Trashpanda Team not support any insallation distribution on linux machines. 

** Windows 
   Executable installator in windows are maked by two different program with dedicated configurations, in three steps
   1. First of all you create jarman-client executable by running =lein uberjar= with default profile
   2. The seconds you ivoke =launch4j= which wrapp, created in directory =target/uberjar/=, jar into exe, and add some jre configurations, parameters, guards(for exampel you get info dialog when jdk not been found on your computer) etc.
   3. And the last step finished by =Inno Setup= which defined in confugred in =installer= folder, finally build =jarman-setup.exe=. 
   
*** Launch4j 
    Launch4j is tool for wrapping =.jar= into windows =.exe= executable file. 
    Whole configuraion, you can find in path =<project-root>\jarman\installer\launch4j.xml=. 
    Remember, program support only /absolute paths/.
    
    You can build executable by runnig dedicated CLI toolkit
    #+begin_src bat
      & launch4jc.exe <project-root>\jarman\installer\launch4j.xml
    #+end_src

    or altirnatively go into =jarman/jarman= project path, and in powershell run
    #+begin_src sh
      lein launch4j
    #+end_src
    plugin automaticaly build executable and put it into =installer= directory. 

*** Inno Setup
    Program help automatically create setup processing gui wizard. Mainly all needed configuration are declared in =installer/setup-client.iss=. That's file define what, where will be installed. To understading more, just open the file. 
    After program finished to work, file =jarman-setup.exe= will be created in =inno-target= folder.
    #+begin_src bat
      & ISCC.exe <project-root>\jarman\installer\setup-client.iss
    #+end_src
   
*** Post install file structure
    
    Jarman files dividing logicaly as "something that is just program" and "all user data, configuration, plugins". 
    
    - =C:\\P.. F..\\Jarman\\= - is main folder where =Jarman.exe=, and related binary or another application must be located. 
    - =${USERHOME}\.jarman.d= - directory must contain all needed plugin, configurations, backups and any file dumps.
    - =${USERHOME}\.jarman= - central configuration file, which help to set some behavior pattern for jarman
    - =${USERHOME}\.jarman.data= - in this file we define all configuraiton to database that up whole jarman buisness logic infrastructure. 
